// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import AuthProvider from "./providers/auth";
import ToastProvider from "./providers/toast";
// import SessionTimeout from "@/components/SessionTimeout";
import Wp from "./components/Wp";
import "react-toastify/dist/ReactToastify.css";

// Configurar as fontes

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["700", "100", "200", "300", "400", "500", "600", "800", "900"], // Pesos que deseja usar
  variable: "--font-poppins", // Variável CSS para Poppins
});

// export const metadata: Metadata = {
//   title: "Incentivecare",
//   description:
//     "Incentivecare, um programa que abrange diversas soluções entre seguros, assistências e benefícios, desenvolvidos para cuidar de você e quem você ama.",
// };

export const metadata: Metadata = {
  title: "Incentivecare",
  description: "Pacote de benefícios",
  keywords: [
    "seguro",
    "assistência",
    "Tem saude",
    "MAPFRE",
    "Pacote de benefícios",
    "gestão de RH",
    "recursos humanos",
    "departamento pessoal",
    "folha de pagamento",
    "automação de RH",
    "onboarding",
    "offboarding",
    "gestão trabalhista",
    "benefícios corporativos",
    "plano de benefícios",
    "seguro MAPFRE",
    "desenvolvimento de sites",
    "sistema para RH",
    "clube de vantagens",
    "produtividade no RH",
    "redução de turnover",
    "assistência funeral",
    "assistência pet",
    "automação de processos",
    "conformidade legal",
    "RH estratégico",
  ],
  icons: {
    icon: "/images/logo.png",
  },
  openGraph: {
    type: "website",
    locale: "pt_BR",
    url: "https://Incentivecare.com.br",
    title: "Incentivecare",
    description: "Tem saude e seguro MAPFRE",
    siteName: "Incentivecare",
    images: [
      {
        url: "/images/logo.png",
        width: 1200,
        height: 630,
        alt: "Incentivecare",
        type: "image/svg+xml",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Incentivecare",
    description: "Pacote de beneficios tem saude e seguro MAPFRE",
    images: ["/logo.svg"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={` ${poppins.variable}`}>
      {/* <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Lobster&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/favicon.png" type="image/x-icon" />
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-G3VYX43SJJ"
        ></script>

        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-G3VYX43SJJ');
            `,
          }}
        />
      </head> */}
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Lobster&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.png" type="image/x-icon" />

        {/* Google Analytics */}
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-G3VYX43SJJ"
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-G3VYX43SJJ');
      `,
          }}
        />

        {/* Meta Pixel */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
        !function(f,b,e,v,n,t,s)
        {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};
        if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
        n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];
        s.parentNode.insertBefore(t,s)}(window, document,'script',
        'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '1425770951972688');
        fbq('track', 'PageView');
      `,
          }}
        />
        <noscript>
          <img
            height="1"
            width="1"
            style={{ display: "none" }}
            src="https://www.facebook.com/tr?id=1425770951972688&ev=PageView&noscript=1"
          />
        </noscript>
      </head>
      <body>
        <AuthProvider>
          <ToastProvider>
            {/* <SessionTimeout /> */}
            {children}
            <Wp />
          </ToastProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
